apiVersion: v1
kind: Service
metadata:
  labels:
    app: tekton-trigger-webhook
  name: tekton-trigger-webhook
  namespace: tekton-listener-system
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: tekton-pipelines-webhook
